export const data = {
	projects: [
		{
			name: 'Threat Stack website',
			desc:
				'Built custom Wordpress theme from scratch. Features of the site include improved UI/UX, improved performance, custom post types, custom fields, ES6+, and many more.',
			url: 'https://www.threatstack.com',
			image: 'https://timlisiecki.github.io/images/portfolio/threat-stack.png',
			featured: true,
			tech: ['HTML', 'CSS', 'Wordpress', 'ES6', 'PHP'],
		},
		{
			name: 'Software Engineering Self-directed Guide',
			desc: 'A guide for aspiring software developers who want to learn on their own that includes recommended courses and resources.',
			url: 'https://timlisiecki.github.io/swe-self-directed-guide/',
			image: 'https://timlisiecki.github.io/images/portfolio/swe-guide.png',
			featured: true,
			tech: ['HTML', 'CSS'],
		},
		{
			name: 'Scratch Ticket App',
			desc: 'Scratch ticket game created using Javascript.',
			url: 'https://timlisiecki.github.io/web-dev-scratch-tickets/',
			github: 'https://github.com/timlisiecki/web-dev-scratch-tickets',
			image: 'https://timlisiecki.github.io/images/portfolio/scratch-tix.png',
			featured: true,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
		{
			name: 'Blue Collar Coding',
			desc: 'Freelance web services providing modern, mobile-optimized websites and web apps for small business.',
			url: 'https://bluecollarcoding.com/',
			github: 'https://github.com/timlisiecki/blue-collar-coding',
			image: 'https://timlisiecki.github.io/images/portfolio/bcc2.png',
			featured: false,
			tech: ['JavaScript', 'React', 'CSS'],
		},
		{
			name: 'Rock, Paper, Scrissors Game',
			desc: 'A simple game of Rock, Paper, Scissors built with vanilla JavaScript.',
			url: 'https://timlisiecki.github.io/js-rock-paper-scissors/',
			github: 'https://github.com/timlisiecki/js-rock-paper-scissors',
			image: 'https://timlisiecki.github.io/images/portfolio/rock-paper-scissors.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
		{
			name: 'RoboFriends App',
			desc: 'Progressive Web App using React and Redux.',
			url: 'https://timlisiecki.github.io/robofriends-with-redux/',
			github: 'https://github.com/timlisiecki/robofriends-with-redux',
			image: 'https://timlisiecki.github.io/images/portfolio/robofriends-redux.png',
			featured: false,
			tech: ['React', 'Redux', 'PWA'],
		},
		{
			name: 'React To Do App',
			desc: 'To Do app built with React. Uses third-party authorization to register/login.',
			url: 'http://reacttodoapp.herokuapp.com/',
			github: 'https://github.com/timlisiecki/city-ofchampions',
			image: 'https://timlisiecki.github.io/images/portfolio/react-todo-app.png',
			featured: false,
			tech: ['React', 'HTML', 'SCSS'],
		},
		{
			name: 'React Weather App',
			desc: 'Weather app built with React. Uses third-party authorization to register/login.  ',
			url: 'http://powerful-cliffs-34356.herokuapp.com/',
			github: 'https://github.com/timlisiecki/react-weather-app',
			image: 'https://timlisiecki.github.io/images/portfolio/react-weather-app.png',
			featured: false,
			tech: ['React', 'HTML', 'SCSS'],
		},
		{
			name: 'Budget App',
			desc: 'Object Oriented Programming JavaScript Budget App.',
			url: 'https://timlisiecki.github.io/budget-app/',
			github: 'https://github.com/timlisiecki/budget-app',
			image: 'https://timlisiecki.github.io/images/portfolio/budget.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
		{
			name: 'Yelp Camp',
			desc:
				'Fictional web application for reviewing campsites, using Node.js, ExpressJS, Mongoose, Passport, RESTful Routing, jQuery, Javascript, and Bootstrap.',
			url: 'https://yelpcamp-demo.herokuapp.com/',
			github: 'https://github.com/timlisiecki/udemy-bootcamp-YelpCamp',
			image: 'https://timlisiecki.github.io/images/portfolio/yelpcamp.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS', 'Express'],
		},
		{
			name: 'Dice Game',
			desc: '2-Player dice game built by JavaScript.',
			url: 'https://timlisiecki.github.io/dice-game/',
			github: 'https://github.com/timlisiecki/dice-game',
			image: 'https://timlisiecki.github.io/images/portfolio/dice.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
		{
			name: 'Color Guessing Game',
			desc: 'Guessing game using JavaScript to choose the correct color square given a amount of red, green, blue (RGB) color system.',
			url: 'https://timlisiecki.github.io/guess_color/',
			github: 'https://github.com/timlisiecki/guess_color',
			image: 'https://timlisiecki.github.io/images/portfolio/guesscolor.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
		{
			name: 'City of Champions',
			desc: 'Object Oriented Programming JavaScript project displaying content dynamically.',
			url: 'https://timlisiecki.github.io/city-ofchampions/',
			github: 'https://github.com/timlisiecki/city-ofchampions',
			image: 'https://timlisiecki.github.io/images/portfolio/champions.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
		{
			name: 'Patatap Clone',
			desc:
				'A clone of Patatap.com, utilizing JavaScript to animate the HTML5 Canvas to create colors and sounds by the keyboard. (Desktop-Only)',
			url: 'https://timlisiecki.github.io/patatap-clone/',
			github: 'https://github.com/timlisiecki/patatap-clone',
			image: 'https://timlisiecki.github.io/images/portfolio/patatapclone.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
		{
			name: 'Todo List',
			desc: 'Simple to do list using jQuery to add, complete, and delete a list item.',
			url: 'https://timlisiecki.github.io/to-do-list/',
			github: 'https://github.com/timlisiecki/to-do-list',
			image: 'https://timlisiecki.github.io/images/portfolio/todolist.png',
			featured: false,
			tech: ['JavaScript', 'HTML', 'CSS'],
		},
	],
	jobs: [
		{
			company: 'Threat Stack',
			title: 'Full Stack Web Developer',
			dates: 'May 2019 - Present',
			desc:
				"In-house full-stack web developer. Developing and managing all aspects of the website, including Development, Staging, and Production environments. In November 2019, I launched a redesigned website that I had built from scratch with the goal of improved UI/UX, to increase conversions, and to better present educational materials. Built customized interactive features into the website using PHP, HTML, CSS, jQuery, Bootstrap, REST API's, and other web development technologies. Developed site architecture into reusable modules and components. Between February and June, 2020, I planned, developed, tested, and deployed a resource center integrated into the website with an optimized gated-resource feature and improved search capabilities. Collaborating with cross-functional teams in order to best present the product and services that the company offers.",
			url: 'https://www.threatstack.com',
			industry: 'technology',
		},
		{
			company: 'Blue Collar Coding',
			title: 'Web Developer',
			dates: 'Sep 2018 - Present',
			desc:
				'[ad-hoc] Created Blue Collar Coding, a freelance website for developing websites and web apps for small businesses. Designing and developing websites with user experience and interface in mind. Maintaining and updating websites as required. Currently part-time serving a limited number of clients.',
			url: 'https://bluecollarcoding.com',
			industry: 'technology',
		},
		{
			company: 'Elromco, Inc',
			title: 'Web Developer',
			dates: 'Dec 2018 - Mar 2019',
			desc:
				'Web developer in a small team for a moving software startup. Main responsibilities include building custom websites for moving companies, integrating the software with clients’ websites, and creating processes to make company and products scalable. Also set up foundation for offering SEO services.',
			url: 'https://elromco.com',
			industry: 'technology',
		},
		{
			company: 'Massachusetts Bay Lines',
			title: 'Web Marketing Manager',
			dates: 'May 2017 - Dec 2018',
			desc:
				'Web Marketing Manager with responsibilities in marketing and website management. Other responsibilities include training employees, creating and implementing 40-page training program, documenting processes and procedures, hands-on training, and assisting in scheduling and hiring.',
			url: 'https://massbaylines.com',
			industry: 'technology',
		},
		{
			company: 'Freelance',
			title: 'Front End Web Developer',
			dates: 'Jan 2016 - Dec 2018',
			desc:
				'[part-time] Web Developer with a focus on Front End Development. Developing responsive design projects. Proficiency in HTML, CSS, and JavaScript. Utilizing frameworks and libraries such as Bootstrap, jQuery, React, and Node.',
			url: '',
			industry: 'technology',
		},
		{
			company: 'Massachusetts Bay Lines',
			title: 'Captain',
			dates: 'Apr 2009 - Present',
			desc: '[part-time/seasonal] Captain of fleet of five vessels in Boston Harbor. See LinkedIn profile for more information.',
			url: 'https://massbaylines.com',
			industry: 'maritime',
		},
	],
	resources: [
		{
			title: 'The Complete Junior to Senior Web Developer Roadmap (2019)',
			author: 'Andrei Neagoie',
			url: 'https://www.udemy.com/the-complete-junior-to-senior-web-developer-roadmap/',
			image: 'https://i.udemycdn.com/course/240x135/1650610_2673_5.jpg',
			type: 'Course',
			featured: true,
		},
		{
			title: 'JavaScript Algorithms and Data Structures Masterclass',
			author: 'Colt Steele',
			url: 'https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/',
			image: 'https://img-a.udemycdn.com/course/240x135/1406344_1d65_3.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'Node.js API Masterclass With Express & MongoDB',
			author: 'Brad Traversy',
			url: 'https://www.udemy.com/course/nodejs-api-masterclass/',
			image: 'https://img-a.udemycdn.com/course/240x135/2609434_23cf_2.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'React For The Rest Of Us',
			author: 'Brad Schiff',
			url: 'https://www.udemy.com/course/react-for-the-rest-of-us/',
			image: 'https://img-a.udemycdn.com/course/240x135/1439744_ba20_5.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'Become a WordPress Developer: Unlocking Power With Code',
			author: 'Brad Schiff',
			url: 'https://www.udemy.com/course/become-a-wordpress-developer-php-javascript/',
			image: 'https://img-a.udemycdn.com/course/240x135/1010586_b622_3.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'The Complete React Web App Developer Course',
			author: 'Andrew Mead',
			url: 'https://www.udemy.com/the-complete-react-web-app-developer-course/',
			image: 'https://i.udemycdn.com/course/240x135/755128_8928.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'Git a Web Developer Job: Mastering the Modern Workflow',
			author: 'Brad Schiff',
			url: 'https://www.udemy.com/git-a-web-developer-job-mastering-the-modern-workflow/',
			image: 'https://i.udemycdn.com/course/240x135/818990_57c0_3.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'Automate Web Development with Gulp JS',
			author: 'Andrew Mead',
			url: 'https://www.udemy.com/learn-gulp/',
			image: 'https://i.udemycdn.com/course/240x135/284076_749f_7.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'The Complete JavaScript Course: Build Real Projects!',
			author: 'Jonas Schmedtmann',
			url: 'https://www.udemy.com/the-complete-javascript-course/',
			image: 'https://i.udemycdn.com/course/240x135/851712_fc61_5.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'The Web Developer Bootcamp',
			author: 'Colt Steele',
			url: 'https://www.udemy.com/the-web-developer-bootcamp/',
			image: 'https://i.udemycdn.com/course/240x135/625204_436a_2.jpg',
			type: 'Course',
			featured: false,
		},
		{
			title: 'JavaScript - The Good Parts',
			author: 'Douglas Crockford',
			url: 'http://shop.oreilly.com/product/9780596517748.do',
			image: 'https://covers.oreillystatic.com/images/9780596517748/lrg.jpg',
			type: 'Book',
			featured: false,
		},
		{
			title: 'Programming JavaScipt Applications',
			author: 'Eric Elliott',
			url: 'https://www.oreilly.com/library/view/programming-javascript-applications/9781491950289/',
			image: 'https://www.oreilly.com/library/cover/9781491950289/360h/',
			type: 'Book',
			featured: true,
		},
		{
			title: 'The Unicorn Project',
			author: 'Gene Kim',
			url: 'https://www.amazon.com/Unicorn-Project-Developers-Disruption-Thriving/dp/1942788762/',
			image: 'https://images-na.ssl-images-amazon.com/images/I/51A4T36jisL._SX334_BO1,204,203,200_.jpg',
			type: 'Book',
			featured: true,
		},
	],
};
